repos:
  - repo: local
    hooks:
      - id: poe-precommit
        name: poe-precommit
        entry: uv run poe precommit
        language: system
        pass_filenames: false
        stages: [pre-commit] 