# AUTOGENERATED! DO NOT EDIT! File to edit: ../1-4.ipynb.

# %% auto 0
__all__ = ['identity_tensor']

# %% ../1-4.ipynb 0
import torch

# %% ../1-4.ipynb 5
def identity_tensor(order: int, dim: int, dtype: torch.dtype = torch.float32) -> torch.Tensor:
    dims = [dim] * order
    I = torch.zeros(*dims, dtype=dtype)
    for i in range(dim):
        indices = [i] * order
        I[tuple(indices)] = 1.

    return I
