"""力学指使用数序描述物理系统的演化规律"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../2-8.ipynb.

# %% auto #0
__all__ = ['heisenberg']

# %% ../../2-8.ipynb #f3f23280
import torch
from .functional import pauli_operator

# %% ../../2-8.ipynb #9b8869a7
def heisenberg(
    *,
    jx: float | torch.Tensor,
    jy: float | torch.Tensor,
    jz: float | torch.Tensor,
    double_precision: bool = False,
    return_matrix: bool = False,
    device: torch.device | None = None,
) -> torch.Tensor:
    """
    Calculate the Hamiltonian of the Heisenberg model.
    Args:
        jx: float | torch.Tensor, the coupling strength of the x-axis.
        jy: float | torch.Tensor, the coupling strength of the y-axis.
        jz: float | torch.Tensor, the coupling strength of the z-axis.
        double_precision: bool, whether to use double precision.
        return_matrix: bool, whether to return the Hamiltonian in matrix form. By default, the Hamiltonian is returned in tensor form.
        device: torch.device | None, the device to create the Hamiltonian on. If None, infer from tensor coefficients or use CPU.
    Returns:
        torch.Tensor, the Hamiltonian of the Heisenberg model.
    """
    if device is None:
        for coefficient in [jx, jy, jz]:
            if isinstance(coefficient, torch.Tensor):
                device = coefficient.device
                break
    if device is not None:
        jx = jx.to(device=device) if isinstance(jx, torch.Tensor) else jx
        jy = jy.to(device=device) if isinstance(jy, torch.Tensor) else jy
        jz = jz.to(device=device) if isinstance(jz, torch.Tensor) else jz
    pauli_x = pauli_operator(pauli="X", double_precision=double_precision, device=device)
    pauli_y = pauli_operator(pauli="Y", double_precision=double_precision, device=device)
    pauli_z = pauli_operator(pauli="Z", double_precision=double_precision, device=device)
    hamiltonian = (
        jx * torch.einsum("ab, ij -> aibj", pauli_x, pauli_x)
        + jy * torch.einsum("ab, ij -> aibj", pauli_y, pauli_y).real
        + jz * torch.einsum("ab, ij -> aibj", pauli_z, pauli_z)
    )
    hamiltonian /= 4
    if return_matrix:
        return hamiltonian.reshape(4, 4)
    else:
        return hamiltonian
